openapi: 3.0.0
info:
  title: Microsoft Cognitive Services Speech API
  version: 1.0.0
  description: API for Text-to-Speech and Speech-to-Text services

servers:
  - url: https://YOUR_REGION.tts.speech.microsoft.com/cognitiveservices/v1

paths:
  /text-to-speech:
    post:
      summary: Convert text to speech
      operationId: textToSpeech
      requestBody:
        required: true
        content:
          application/ssml+xml:
            schema:
              type: string
      parameters:
        - in: query
          name: language
          schema:
            type: string
          required: true
          description: The language code for TTS
        - in: query
          name: voice
          schema:
            type: string
          required: true
          description: The voice name for TTS
      responses:
        '200':
          description: Successful response
          content:
            audio/mpeg:
              schema:
                type: string
                format: binary

  /speech-to-text:
    post:
      summary: Convert speech to text
      operationId: speechToText
      requestBody:
        required: true
        content:
          audio/wav:
            schema:
              type: string
              format: binary
      parameters:
        - in: query
          name: language
          schema:
            type: string
          required: true
          description: The language code for STT
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  text:
                    type: string

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Ocp-Apim-Subscription-Key

security:
  - ApiKeyAuth: []
